grid:
  width: 5
  height: 5
  kind: TOROIDAL
obstacles:
  - x: 1
    y: 1
  - x: 0
    y: 4
rovers:
  - position:
      coordinates:
        x: 1
        y: 2
      orientation: NORTH
    commands:
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - MOVE
  - position:
      coordinates:
        x: 3
        y: 3
      orientation: EAST
    commands:
      - MOVE
      - MOVE
      - RIGHT
      - MOVE
      - MOVE
      - RIGHT
      - MOVE
      - RIGHT
      - RIGHT
      - MOVE
