grid:
  width: 5
  height: 5
  kind: RECTANGULAR
obstacles:
  - x: 3
    y: 3
  - x: 4
    y: 3
rovers:
  - position:
      coordinates:
        x: 1
        y: 2
      orientation: NORTH
    commands:
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - LEFT
        - MOVE
        - MOVE
    explorationRadius: 1
  - position:
      coordinates:
        x: 3
        y: 3
      orientation: EAST
    commands:
      - MOVE
      - MOVE
      - RIGHT
      - MOVE
      - MOVE
      - RIGHT
      - MOVE
      - RIGHT
      - RIGHT
      - MOVE
    explorationRadius: 0
